require("util")

map("n", "0", "^")
map("v", "0", "^")
map("n", ".", "$", {noremap = true})
map("v", ".", "$")
map("n", "<Space>", "zz <Bar> :noh<Bar>echo<cr>")
map("v", "<Space>", "zz")
map("n", "P", "o<Esc>p")
map("n", ",", ".")
map("n", "=", "}")
map("v", "=", "}")
map("n", "-", "{")
map("v", "-", "{")
map("n", "p", "pgvy")
