local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.config/nvim/plugged')
  Plug('vim-airline/vim-airline')
  Plug('vim-airline/vim-airline-themes')
  Plug('nvim-treesitter/nvim-treesitter', {['do'] = ':TSUpdate'})
  Plug('nvim-tree/nvim-web-devicons')
  Plug('nvim-tree/nvim-tree.lua')
  Plug("ellisonleao/gruvbox.nvim")
  Plug('nvim-lua/popup.nvim')
  Plug('nvim-lua/plenary.nvim')
  Plug('BurntSushi/ripgrep')
  Plug('nvim-telescope/telescope.nvim', { tag= '0.1.0' })
  Plug('nvim-telescope/telescope-file-browser.nvim')
  Plug('neoclide/coc.nvim', {branch= 'release'})
  Plug('tpope/vim-repeat')
  Plug('ggandor/leap.nvim')
  Plug('Pocco81/auto-save.nvim')
  Plug('ahmedkhalf/project.nvim')
  Plug('voldikss/vim-floaterm')
  Plug('terrortylor/nvim-comment')
  Plug('mhinz/vim-signify')
  Plug('google/vim-maktaba')
  Plug('google/vim-codefmt')
  Plug('google/vim-glaive')
vim.call('plug#end')
